#
# (c) 2022 OpenTHC, Inc.
# This file is part of OpenTHC Pub released under MIT License
# SPDX-License-Identifier: MIT
#
# OpenTHC API
#

openapi: 3.0.2

info:
  title: OpenTHC Pub API
  description: OpenTHC Pub API reference
  version: "420.22.123"
  contact:
    name: OpenTHC, Inc.
    url: https://openthc.com/
    email: code@openthc.com
  license:
    name: MIT
  termsOfService: https://openthc.com/about/tos


externalDocs:
  description: "Find out more about OpenTHC"
  url: "https://openthc.com"


#
# Servers
servers:
  - url: https://pub.openthc.example.com
    description: Example Implementation
  - url: https://YOUR_HOST/YOUR/PATH
    description: You can install to sub-host or sub-path

tags:
  - name: Message
    description: Sending a Message
  - name: Profile
    description: Profile Specific endpoints for message sharing.


#
# Componenets
components:
  requestBodies:
    Profile_Create:
      description: "Create an Profile"
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                description: "A Name"
              link:
                description: "Link to Homepage"

    Profile_Update:
      description: "Update an Profile"
      content:
        application/json:
          schema:
            type: object
            properties:
              crypt:
                description: "Encrypted Data Blob, Base64"
              nonce:
                description: "The nonce for the encrypted data"

    # Message_Create:
    #   description: "Create a Message to an Profile"
    #   content:
    #     application/json:
    #       schema:
    #         type: object
    #         properties:
    #           crypt:
    #             description: "Encrypted Data Blob, Base64"
    #           nonce:
    #             description: "The nonce for the encrypted data"

  responses:
    Profile:
      description: "Profile Information"
      content:
        application/json:
          schema:
            properties:
              data:
                description: "Some kind of data, an array of objects or a single object"
              meta:
                description: "Additional Helpful info, generally an object or array of objects"

    Message:
      description: "A Single Message"
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                description: "Some kind of data, an array of objects or a single object"
              meta:
                description: "Additional Helpful info, generally an object or array of objects"
    System:
      description: "A system class message"
      content:
        application/json:
          schema:
            properties:
              data:
                description: "Some Interesting Data"
              meta:
                description: "Might include a note"

  # schemas:
  #   $ref: 'components/schema.yaml'


#
# Paths
paths:
  "/$MESSAGE_PK/MESSAGE.FILE":
    post:
      summary: "Create or Update a Message"
      tags: [ "Message" ]
      responses:
        200:
          $ref: 'components/responses/Message'
        403:
          $ref: 'components/responses/System'
        404:
          $ref: 'components/responses/System'

    put:
      summary: "Create or Update a Message"
      tags: [ "Message" ]
      responses:
        200:
          $ref: 'components/responses/System'
        403:
          $ref: 'components/responses/System'
        404:
          $ref: 'components/responses/System'
    get:
      summary: "Get the Message"
      tags: [ "Message" ]
      responses:
        200:
          $ref: 'components/responses/Message'
        404:
          $ref: 'components/responses/System'
    delete:
      summary: "Delete the Message"
      tags: [ "Message" ]
      responses:
        200:
          $ref: 'components/responses/System'
        403:
          $ref: 'components/responses/System'
        404:
          $ref: 'components/responses/System'

  "/$PROFILE_PK":
    get:
      summary: "Get the JSON details for the specific Profile"
      tags: [ "Profile" ]
      responses:
        200:
          $ref: 'components/responses/Profile'
        404:
          $ref: 'components/responses/System'
    post:
      summary: "Create or Update Public Key"
      description: "Creates and registers a public key endpoint"
      tags: [ "Profile" ]
      requestBody:
        description: Some JSON describing the profile
        required: false
        content:
          application/json:
            schema:
              oneOf:
                - $ref: 'components/requestBodies/Profile_Create'
                - $ref: 'components/requestBodies/Profile_Update'
      responses:
        200:
          $ref: 'components/responses/System'
        201:
          $ref: 'components/responses/System'
        403:
          $ref: 'components/responses/System'
    put:
      summary: "Like POST"
      tags: [ "Profile" ]
      responses:
        200:
          $ref: 'components/responses/System'
        201:
          $ref: 'components/responses/System'
        403:
          $ref: 'components/responses/System'

  "/$PROFILE_PK/$MESSAGE_PK":
    post:
      summary: "Create a Message"
      description: "Create a Message to a Specific Profile"
      tags: [ "Profile" ]
      responses:
        201:
          $ref: 'components/responses/System'
    put:
      summary: "Like POST"
      tags: [ "Profile" ]
      responses:
        200:
          $ref: 'components/responses/System'
        201:
          $ref: 'components/responses/System'
    delete:
      summary: "Delete a Message from your incoming queue"
      description: "Delete a Message"
      tags: [ "Profile" ]
      responses:
        200:
          $ref: 'components/responses/System'
        403:
          $ref: 'components/responses/System'
        404:
          $ref: 'components/responses/System'
